<?php
/** @var $block Magento\Framework\View\Element\Template */

?>

<div class="payment-methods-wrapper"> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/amex.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/mastercard.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/visa.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/hipercard.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/elo.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/diners.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/paypal.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/pix.png'); ?>" /> 
    <img src="<?php echo $block->getViewFileUrl('images/footer/boleto.png'); ?>" /> 
</div> 
